library("ggplot2")

##1N
total_1N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/1N.total.transcripts", header=T)
cor.test(total_1N$Bowtie2_RSEM_FPKM, total_1N$Tophat2_Cufflinks_FPKM, method="pearson")
cor.test(total_1N$Bowtie2_RSEM_FPKM, total_1N$Salmon_Tximport_FPKM, method="pearson")
cor.test(total_1N$Tophat2_Cufflinks_FPKM, total_1N$Salmon_Tximport_FPKM, method="pearson")
br_tc_1N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/1N.br_overlap_tc.transcripts", header=T)
cor.test(br_tc_1N$Bowtie2_RSEM_FPKM, br_tc_1N$Tophat2_Cufflinks_FPKM, method="pearson")
br_st_1N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/1N.br_overlap_st.transcripts", header=T)
cor.test(br_st_1N$Bowtie2_RSEM_FPKM, br_st_1N$Salmon_Tximport_FPKM, method="pearson")
tc_st_1N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/1N.tc_overlap_st.transcripts", header=T)
cor.test(tc_st_1N$Tophat2_Cufflinks_FPKM, tc_st_1N$Salmon_Tximport_FPKM, method="pearson")

##1T
total_1T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/1T.total.transcripts", header=T)
cor.test(total_1T$Bowtie2_RSEM_FPKM, total_1T$Tophat2_Cufflinks_FPKM, method="pearson")
cor.test(total_1T$Bowtie2_RSEM_FPKM, total_1T$Salmon_Tximport_FPKM, method="pearson")
cor.test(total_1T$Tophat2_Cufflinks_FPKM, total_1T$Salmon_Tximport_FPKM, method="pearson")
br_tc_1T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/1T.br_overlap_tc.transcripts", header=T)
cor.test(br_tc_1T$Bowtie2_RSEM_FPKM, br_tc_1T$Tophat2_Cufflinks_FPKM, method="pearson")
br_st_1T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/1T.br_overlap_st.transcripts", header=T)
cor.test(br_st_1T$Bowtie2_RSEM_FPKM, br_st_1T$Salmon_Tximport_FPKM, method="pearson")
tc_st_1T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/1T.tc_overlap_st.transcripts", header=T)
cor.test(tc_st_1T$Tophat2_Cufflinks_FPKM, tc_st_1T$Salmon_Tximport_FPKM, method="pearson")

##2N
total_2N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/2N.total.transcripts", header=T)
cor.test(total_2N$Bowtie2_RSEM_FPKM, total_2N$Tophat2_Cufflinks_FPKM, method="pearson")
cor.test(total_2N$Bowtie2_RSEM_FPKM, total_2N$Salmon_Tximport_FPKM, method="pearson")
cor.test(total_2N$Tophat2_Cufflinks_FPKM, total_2N$Salmon_Tximport_FPKM, method="pearson")
br_tc_2N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/2N.br_overlap_tc.transcripts", header=T)
cor.test(br_tc_2N$Bowtie2_RSEM_FPKM, br_tc_2N$Tophat2_Cufflinks_FPKM, method="pearson")
br_st_2N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/2N.br_overlap_st.transcripts", header=T)
cor.test(br_st_2N$Bowtie2_RSEM_FPKM, br_st_2N$Salmon_Tximport_FPKM, method="pearson")
tc_st_2N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/2N.tc_overlap_st.transcripts", header=T)
cor.test(tc_st_2N$Tophat2_Cufflinks_FPKM, tc_st_2N$Salmon_Tximport_FPKM, method="pearson")

##2T
total_2T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/2T.total.transcripts", header=T)
cor.test(total_2T$Bowtie2_RSEM_FPKM, total_2T$Tophat2_Cufflinks_FPKM, method="pearson")
cor.test(total_2T$Bowtie2_RSEM_FPKM, total_2T$Salmon_Tximport_FPKM, method="pearson")
cor.test(total_2T$Tophat2_Cufflinks_FPKM, total_2T$Salmon_Tximport_FPKM, method="pearson")
br_tc_2T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/2T.br_overlap_tc.transcripts", header=T)
cor.test(br_tc_2T$Bowtie2_RSEM_FPKM, br_tc_2T$Tophat2_Cufflinks_FPKM, method="pearson")
br_st_2T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/2T.br_overlap_st.transcripts", header=T)
cor.test(br_st_2T$Bowtie2_RSEM_FPKM, br_st_2T$Salmon_Tximport_FPKM, method="pearson")
tc_st_2T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/2T.tc_overlap_st.transcripts", header=T)
cor.test(tc_st_2T$Tophat2_Cufflinks_FPKM, tc_st_2T$Salmon_Tximport_FPKM, method="pearson")

##3N
total_3N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/3N.total.transcripts", header=T)
cor.test(total_3N$Bowtie2_RSEM_FPKM, total_3N$Tophat2_Cufflinks_FPKM, method="pearson")
cor.test(total_3N$Bowtie2_RSEM_FPKM, total_3N$Salmon_Tximport_FPKM, method="pearson")
cor.test(total_3N$Tophat2_Cufflinks_FPKM, total_3N$Salmon_Tximport_FPKM, method="pearson")
br_tc_3N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/3N.br_overlap_tc.transcripts", header=T)
cor.test(br_tc_3N$Bowtie2_RSEM_FPKM, br_tc_3N$Tophat2_Cufflinks_FPKM, method="pearson")
br_st_3N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/3N.br_overlap_st.transcripts", header=T)
cor.test(br_st_3N$Bowtie2_RSEM_FPKM, br_st_3N$Salmon_Tximport_FPKM, method="pearson")
tc_st_3N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/3N.tc_overlap_st.transcripts", header=T)
cor.test(tc_st_3N$Tophat2_Cufflinks_FPKM, tc_st_3N$Salmon_Tximport_FPKM, method="pearson")

##3T
total_3T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/3T.total.transcripts", header=T)
cor.test(total_3T$Bowtie2_RSEM_FPKM, total_3T$Tophat2_Cufflinks_FPKM, method="pearson")
cor.test(total_3T$Bowtie2_RSEM_FPKM, total_3T$Salmon_Tximport_FPKM, method="pearson")
cor.test(total_3T$Tophat2_Cufflinks_FPKM, total_3T$Salmon_Tximport_FPKM, method="pearson")
br_tc_3T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/3T.br_overlap_tc.transcripts", header=T)
cor.test(br_tc_3T$Bowtie2_RSEM_FPKM, br_tc_3T$Tophat2_Cufflinks_FPKM, method="pearson")
br_st_3T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/3T.br_overlap_st.transcripts", header=T)
cor.test(br_st_3T$Bowtie2_RSEM_FPKM, br_st_3T$Salmon_Tximport_FPKM, method="pearson")
tc_st_3T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/3T.tc_overlap_st.transcripts", header=T)
cor.test(tc_st_3T$Tophat2_Cufflinks_FPKM, tc_st_3T$Salmon_Tximport_FPKM, method="pearson")

##4N
total_4N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/4N.total.transcripts", header=T)
cor.test(total_4N$Bowtie2_RSEM_FPKM, total_4N$Tophat2_Cufflinks_FPKM, method="pearson")
cor.test(total_4N$Bowtie2_RSEM_FPKM, total_4N$Salmon_Tximport_FPKM, method="pearson")
cor.test(total_4N$Tophat2_Cufflinks_FPKM, total_4N$Salmon_Tximport_FPKM, method="pearson")
br_tc_4N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/4N.br_overlap_tc.transcripts", header=T)
cor.test(br_tc_4N$Bowtie2_RSEM_FPKM, br_tc_4N$Tophat2_Cufflinks_FPKM, method="pearson")
br_st_4N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/4N.br_overlap_st.transcripts", header=T)
cor.test(br_st_4N$Bowtie2_RSEM_FPKM, br_st_4N$Salmon_Tximport_FPKM, method="pearson")
tc_st_4N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/4N.tc_overlap_st.transcripts", header=T)
cor.test(tc_st_4N$Tophat2_Cufflinks_FPKM, tc_st_4N$Salmon_Tximport_FPKM, method="pearson")

##4T
total_4T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/4T.total.transcripts", header=T)
cor.test(total_4T$Bowtie2_RSEM_FPKM, total_4T$Tophat2_Cufflinks_FPKM, method="pearson")
cor.test(total_4T$Bowtie2_RSEM_FPKM, total_4T$Salmon_Tximport_FPKM, method="pearson")
cor.test(total_4T$Tophat2_Cufflinks_FPKM, total_4T$Salmon_Tximport_FPKM, method="pearson")
br_tc_4T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/4T.br_overlap_tc.transcripts", header=T)
cor.test(br_tc_4T$Bowtie2_RSEM_FPKM, br_tc_4T$Tophat2_Cufflinks_FPKM, method="pearson")
br_st_4T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/4T.br_overlap_st.transcripts", header=T)
cor.test(br_st_4T$Bowtie2_RSEM_FPKM, br_st_4T$Salmon_Tximport_FPKM, method="pearson")
tc_st_4T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/4T.tc_overlap_st.transcripts", header=T)
cor.test(tc_st_4T$Tophat2_Cufflinks_FPKM, tc_st_4T$Salmon_Tximport_FPKM, method="pearson")

##5N
total_5N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/5N.total.transcripts", header=T)
cor.test(total_5N$Bowtie2_RSEM_FPKM, total_5N$Tophat2_Cufflinks_FPKM, method="pearson")
cor.test(total_5N$Bowtie2_RSEM_FPKM, total_5N$Salmon_Tximport_FPKM, method="pearson")
cor.test(total_5N$Tophat2_Cufflinks_FPKM, total_5N$Salmon_Tximport_FPKM, method="pearson")
br_tc_5N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/5N.br_overlap_tc.transcripts", header=T)
cor.test(br_tc_5N$Bowtie2_RSEM_FPKM, br_tc_5N$Tophat2_Cufflinks_FPKM, method="pearson")
br_st_5N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/5N.br_overlap_st.transcripts", header=T)
cor.test(br_st_5N$Bowtie2_RSEM_FPKM, br_st_5N$Salmon_Tximport_FPKM, method="pearson")
tc_st_5N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/5N.tc_overlap_st.transcripts", header=T)
cor.test(tc_st_5N$Tophat2_Cufflinks_FPKM, tc_st_5N$Salmon_Tximport_FPKM, method="pearson")

##5T
total_5T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/5T.total.transcripts", header=T)
cor.test(total_5T$Bowtie2_RSEM_FPKM, total_5T$Tophat2_Cufflinks_FPKM, method="pearson")
cor.test(total_5T$Bowtie2_RSEM_FPKM, total_5T$Salmon_Tximport_FPKM, method="pearson")
cor.test(total_5T$Tophat2_Cufflinks_FPKM, total_5T$Salmon_Tximport_FPKM, method="pearson")
br_tc_5T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/5T.br_overlap_tc.transcripts", header=T)
cor.test(br_tc_5T$Bowtie2_RSEM_FPKM, br_tc_5T$Tophat2_Cufflinks_FPKM, method="pearson")
br_st_5T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/5T.br_overlap_st.transcripts", header=T)
cor.test(br_st_5T$Bowtie2_RSEM_FPKM, br_st_5T$Salmon_Tximport_FPKM, method="pearson")
tc_st_5T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/5T.tc_overlap_st.transcripts", header=T)
cor.test(tc_st_5T$Tophat2_Cufflinks_FPKM, tc_st_5T$Salmon_Tximport_FPKM, method="pearson")

##6N
total_6N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/6N.total.transcripts", header=T)
cor.test(total_5N$Bowtie2_RSEM_FPKM, total_5N$Tophat2_Cufflinks_FPKM, method="pearson")
cor.test(total_5N$Bowtie2_RSEM_FPKM, total_5N$Salmon_Tximport_FPKM, method="pearson")
cor.test(total_5N$Tophat2_Cufflinks_FPKM, total_5N$Salmon_Tximport_FPKM, method="pearson")
br_tc_6N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/6N.br_overlap_tc.transcripts", header=T)
cor.test(br_tc_5N$Bowtie2_RSEM_FPKM, br_tc_5N$Tophat2_Cufflinks_FPKM, method="pearson")
br_st_6N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/6N.br_overlap_st.transcripts", header=T)
cor.test(br_st_5N$Bowtie2_RSEM_FPKM, br_st_5N$Salmon_Tximport_FPKM, method="pearson")
tc_st_6N <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/6N.tc_overlap_st.transcripts", header=T)
cor.test(tc_st_5N$Tophat2_Cufflinks_FPKM, tc_st_5N$Salmon_Tximport_FPKM, method="pearson")

##6T
total_6T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/6T.total.transcripts", header=T)
cor.test(total_5T$Bowtie2_RSEM_FPKM, total_5T$Tophat2_Cufflinks_FPKM, method="pearson")
cor.test(total_5T$Bowtie2_RSEM_FPKM, total_5T$Salmon_Tximport_FPKM, method="pearson")
cor.test(total_5T$Tophat2_Cufflinks_FPKM, total_5T$Salmon_Tximport_FPKM, method="pearson")
br_tc_6T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/6T.br_overlap_tc.transcripts", header=T)
cor.test(br_tc_5T$Bowtie2_RSEM_FPKM, br_tc_5T$Tophat2_Cufflinks_FPKM, method="pearson")
br_st_6T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/6T.br_overlap_st.transcripts", header=T)
cor.test(br_st_5T$Bowtie2_RSEM_FPKM, br_st_5T$Salmon_Tximport_FPKM, method="pearson")
tc_st_6T <- read.table("/leofs/wulin_group/zhangcm/panqf/rna/04_expression/01_gene/04_summary/05_expression_correlation/6T.tc_overlap_st.transcripts", header=T)
cor.test(tc_st_5T$Tophat2_Cufflinks_FPKM, tc_st_5T$Salmon_Tximport_FPKM, method="pearson")
